export const state = () => ({
  list: [
    {
      company: '위펀',
      rank: '매니저',
      department: '개발팀',
      date: '2020. 04 ~ 2021. 06',
      explain: ['스낵24 및 신규 서비스 웹 앱 프론트엔드 개발'],
      project: [
        '고객사 전용 포탈 웹 프론트엔드 개발',
        '고객사 전용 모바일 앱 프론트엔드 개발',
        '신규 서비스 소개 및 회원가입 홈페이지 프론트엔드 개발',
        '무인 결제 키오스크 테블릿 앱 프론트엔드 개발',
        '고객사 임직원 복지용 선물 수령 웹 프론트엔드 개발',
      ],
      skill: [
        'html',
        'css',
        'javascript',
        'vuejs',
        'nuxtjs',
        'nodejs',
        'axios',
        'jquery',
      ],
    },
    {
      company: '라오니스',
      rank: '대리',
      department: '기술지원팀',
      date: '2019. 05 ~ 2020. 02',
      explain: [
        'flash 기술 지원 종료 예정에 따른 기존 e러닝 콘텐츠 html5 변환을 위한 e러닝 프로토타입 개발',
        '신규 e러닝 콘텐츠 개발',
        '계약 업체의 LMS 환경 분석 후 콘텐츠 포팅',
        '포팅 후 오류 확인 및 수정 작업 등의 기술지원',
        '기술지원팀 일정관리 등의 pm',
      ],
      project: [
        'flash 기술 지원 종료 예정에 따른 기존 e러닝 콘텐츠 html5 변환을 위한 e러닝 프로토타입 개발',
        'html5 변환을 위한 작업 지원 nodejs 프로그램 개발',
        '삼성전자 환경안전그룹 건강검진교육 scorm 기반 html5 콘텐츠 개발',
        '삼성전자 환경안전그룹 연구실책임자교육 scorm 기반 html5 콘텐츠 개발',
        '삼성전자 환경안전그룹 피난훈련교육 scorm 기반 html5 콘텐츠 개발',
        '삼성전자 환경안전그룹 피난훈련교육 scorm 기반 html5 콘텐츠 개발',
        '한기대 인디자인,일러스트 교육 html5 콘텐츠 외주 개발',
        '세종어학당 한국어 교육 html5 콘텐츠 외주 개발',
        '납품업체별 LMS 환경에 따른 콘텐츠 포팅 및 오류 수정',
      ],
      skill: ['html', 'css', 'javascript', 'reactjs', 'webpack', 'nodejs'],
    },
    {
      company: '한국미디어네트워크',
      rank: '사원',
      department: '개발기획부',
      date: '2017. 11 ~ 2019. 03',
      explain: [
        '언론사 PC,MOBILE 웹 유지보수',
        '신규 사업 PC,MOBILE 웹 메인 개발업무를 담당',
        '퇴사후 3개월간 프리랜서 계약 (2019.01~2019.03)',
      ],
      project: [
        '한국아이닷컴,데일리한국,스포츠한국,주간한국,소년한국,골프한국,아이뉴스 / PC,MOBILE 웹 유지보수',
        '월드컵톡 / PC,MOBILE 웹 개발',
        '팬케이크 / PC,MOBILE 웹 개발',
      ],
      skill: ['html', 'css', 'javascript', 'jquery', 'php', 'mysql'],
    },
    {
      company: '위너스톡',
      rank: '사원',
      department: '기술개발실',
      date: '2016. 09 ~ 2017. 09',
      explain: [
        '마케팅,광고,웹에이전시 관련 웹사이트 개발 및 유지보수',
        '약 6개 정도의 사이트를 개발 및 기타 계약 업체 사이트 유지보수',
      ],
      project: [
        '바로가기 아이콘 광고상품 / 운영,유지보수',
        '광고영업관리 사이트 / 운영,유지보수',
        '우리동네피트니스 / MOBILE 웹 개발',
        '아이셀러 / PC,MOBILE 웹 개발',
        '하이파오피스 / 워드프레스 기반 웹 개발',
        '오라클 피부과 지점 / PC,MOBILE 웹 개발',
        '오라클 피부과 공용 / PC,MOBILE 웹 개발',
        '보그스타 / PC,MOBILE 웹 개발',
      ],
      skill: [
        'html',
        'css',
        'javascript',
        'jquery',
        'php',
        'codeigniter',
        'mysql',
      ],
    },
  ],
})
