export const state = () => ({
  list: [
    {
      name: '한기대 인디자인,일러스트 교육',
      state: true,
      active: true,
      show: true,
      url: null,
      content: 'html5 콘텐츠 외주 개발',
      desc: 'e러닝 html5 콘텐츠',
      company: '라오니스',
      img: null,
      tag: ['html', 'css', 'javascript', 'jquery'],
    },
    {
      name: '세종어학당 한국어 교육',
      state: true,
      active: true,
      show: true,
      url: null,
      content: 'html5 콘텐츠 외주 개발',
      desc: 'e러닝 html5 콘텐츠',
      company: '라오니스',
      img: null,
      tag: ['html', 'css', 'javascript', 'jquery'],
    },
    {
      name: '삼성전자 환경안전그룹 연구실책임자 교육',
      state: true,
      active: true,
      show: true,
      url: null,
      content: 'scorm 표준 html5 콘텐츠 개발',
      desc: 'e러닝 html5 콘텐츠',
      company: '라오니스',
      img: null,
      tag: ['webpack', 'react', 'html', 'css', 'javascript', 'jquery'],
    },
    {
      name: '삼성전자 환경안전그룹 피난훈련 교육',
      state: true,
      active: true,
      show: true,
      url: null,
      content: 'scorm 표준 html5 콘텐츠 개발',
      desc: 'e러닝 html5 콘텐츠',
      company: '라오니스',
      img: null,
      tag: ['webpack', 'react', 'html', 'css', 'javascript', 'jquery'],
    },
    {
      name: '삼성전자 환경안전그룹 건강검진진단 결과 교육',
      state: true,
      active: true,
      show: true,
      url: null,
      content: 'scorm 표준 html5 콘텐츠 개발',
      desc: 'e러닝 html5 콘텐츠',
      company: '라오니스',
      img: null,
      tag: ['webpack', 'react', 'html', 'css', 'javascript', 'jquery'],
    },
    {
      name: 'html5 프로토타입 개발',
      state: true,
      active: true,
      show: true,
      url: null,
      content: 'flash 콘텐츠 >> mp4,html5 변환을 위한 프로토타입 개발',
      desc: 'e러닝 html5 콘텐츠',
      company: '라오니스',
      img: null,
      tag: ['webpack', 'react', 'html', 'css', 'javascript', 'jquery'],
    },
    {
      name: 'e러닝 콘텐츠 포팅 및 오류 수정',
      state: true,
      active: true,
      show: true,
      url: 'http://www.raonis.co.kr/content/cate_all1.html',
      content: '업체별 LMS 환경에 따른 e러닝 콘텐츠 포팅 및 오류 수정',
      desc: 'e러닝 html5 콘텐츠',
      company: '라오니스',
      img: null,
      tag: ['html', 'css', 'javascript', 'jquery'],
    },
    {
      name: '한국아이닷컴',
      state: true,
      active: true,
      show: true,
      url: 'http://www.hankooki.com/',
      content: '웹 유지보수',
      desc: '언론사 웹사이트',
      company: '한국미디어네트워크',
      img: '/images/01.jpg',
      tag: ['php', 'mysql', 'html', 'css', 'javascript', 'jquery'],
    },
    {
      name: '데일리한국',
      state: true,
      active: true,
      show: true,
      url: 'http://daily.hankooki.com/',
      content: '웹 유지보수',
      desc: '언론사 웹사이트',
      company: '한국미디어네트워크',
      img: '/images/02.jpg',
      tag: ['php', 'mysql', 'css', 'html', 'javascript', 'jquery'],
    },
    {
      name: '스포츠한국',
      state: true,
      active: true,
      show: true,
      url: 'http://sports.hankooki.com/',
      content: '웹 유지보수',
      desc: '언론사 웹사이트',
      company: '한국미디어네트워크',
      img: '/images/03.jpg',
      tag: ['php', 'mysql', 'css', 'html', 'javascript', 'jquery'],
    },
    {
      name: '주간한국',
      state: true,
      active: true,
      show: true,
      url: 'http://weekly.hankooki.com/',
      content: '웹 유지보수',
      desc: '언론사 웹사이트',
      company: '한국미디어네트워크',
      img: '/images/04.jpg',
      tag: ['php', 'mysql', 'css', 'html', 'javascript', 'jquery'],
    },
    {
      name: '소년한국',
      state: true,
      active: true,
      show: true,
      url: 'http://kids.hankooki.com/',
      content: '웹 유지보수',
      desc: '언론사 웹사이트',
      company: '한국미디어네트워크',
      img: '/images/05.jpg',
      tag: ['php', 'mysql', 'css', 'html', 'javascript', 'jquery'],
    },
    {
      name: '골프한국',
      state: true,
      active: true,
      show: true,
      url: 'http://golfhankook.hankooki.com/',
      content: '웹 유지보수',
      desc: '언론사 웹사이트',
      company: '한국미디어네트워크',
      img: '/images/06.jpg',
      tag: ['php', 'mysql', 'css', 'html', 'javascript', 'jquery'],
    },
    {
      name: '아이뉴스',
      state: true,
      active: true,
      show: true,
      url: 'http://eyenews.hankooki.com/',
      content: '웹 유지보수',
      desc: '언론사 웹사이트',
      company: '한국미디어네트워크',
      img: '/images/07.jpg',
      tag: ['php', 'mysql', 'css', 'html', 'javascript', 'jquery'],
    },
    {
      name: '월드컵톡',
      state: true,
      active: false,
      show: true,
      url: null,
      content: '웹 신규 개발 및 유지보수',
      desc: '커뮤니티 웹사이트',
      company: '한국미디어네트워크',
      img: '/images/08.jpg',
      tag: ['php', 'mysql', 'css', 'html', 'javascript', 'jquery', 'gnuboard'],
    },
    {
      name: '팬케이크',
      state: true,
      active: false,
      show: true,
      url: null,
      content: '웹 신규 개발 및 유지보수',
      desc: '아이돌 팬 커뮤니티, 포인트샵 웹사이트',
      company: '한국미디어네트워크',
      img: '/images/09.jpg',
      tag: [
        'php',
        'mysql',
        'css',
        'html',
        'javascript',
        'jquery',
        'gnuboard',
        'youngcart',
      ],
    },
    {
      name: '우리동네피트니스',
      state: true,
      active: false,
      show: true,
      url: null,
      content: '웹 신규 개발 및 유지보수',
      desc: '지역별 피트니스 정보 제공 웹사이트',
      company: '위너스톡',
      img: '/images/10.jpg',
      tag: [
        'php',
        'mysql',
        'css',
        'html',
        'javascript',
        'jquery',
        'daum map api',
      ],
    },
    {
      name: '아이셀러',
      state: true,
      active: false,
      show: true,
      url: null,
      content: '웹 신규 개발 및 유지보수',
      desc: '휴대폰 판매 업체 내부 정보 제공 및 주문 관리 웹사이트',
      company: '위너스톡',
      img: '/images/11.jpg',
      tag: [
        'php',
        'codeigniter',
        'mysql',
        'css',
        'html',
        'javascript',
        'jquery',
        'bootstrap',
      ],
    },
    {
      name: '하이파오피스',
      state: true,
      active: false,
      show: true,
      url: null,
      content: '웹 신규 개발 및 유지보수',
      desc: '사무용가구 제품 소개 및 주문 관리 웹사이트',
      company: '위너스톡',
      img: null,
      tag: ['php', 'mysql', 'wordpress', 'css', 'html', 'javascript', 'jquery'],
    },
    {
      name: '오라클 피부과',
      state: true,
      active: true,
      show: true,
      url: 'http://www.oraclemedicalgroup.com/',
      content: '웹 신규 개발 및 유지보수',
      desc: '피부과 상담 및 정보제공, 지점 및 공용 웹사이트',
      company: '위너스톡',
      img: '/images/13.jpg',
      tag: ['php', 'mysql', 'css', 'html', 'javascript', 'jquery'],
    },
    {
      name: '보그스타',
      state: true,
      active: true,
      show: true,
      url: 'http://www.vogstar.com',
      content: '웹 신규 개발 및 유지보수',
      desc: '골프 용품 제작업체 제품 정보 제공 웹사이트',
      company: '위너스톡',
      img: '/images/14.jpg',
      tag: [
        'php',
        'mysql',
        'css',
        'html',
        'javascript',
        'jquery',
        'google map api',
      ],
    },
  ],
})
